source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls', 'accounts'), namespace='accounts')),
    path('', include('webapp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import UserDetailView, UserUpdateView, AuthorListView, AuthorCreateView, AuthorDetailView, AuthorUpdateView, \
    AuthorDeleteView, BookCreateView, BookDeleteView, BookDetailView, BookListView, BookUpdateView, ReviewCreateView, \
    ReviewDeleteView, ReviewUpdateView, BookShelfView, BookShelfDeleteView

app_name = 'webapp'

urlpatterns = [
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_details'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('author/create/', AuthorCreateView.as_view(), name='author_create'),
    path('author/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
    path('author/<int:pk>/update', AuthorUpdateView.as_view(), name='author_update'),
    path('author/<int:pk>/delete', AuthorDeleteView.as_view(), name='author_delete'),
    path('', BookListView.as_view(), name='book_list'),
    path('book/create/', BookCreateView.as_view(), name='book_create'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book_details'),
    path('book/<int:pk>/update', BookUpdateView.as_view(), name='book_update'),
    path('book/<int:pk>/delete', BookDeleteView.as_view(), name='book_delete'),
    path('book/<int:pk>/review/create/', ReviewCreateView.as_view(), name='review_create'),
    path('review/<int:pk>/update', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete', ReviewDeleteView.as_view(), name='review_delete'),
    path('book/<int:pk>/add', BookShelfView.as_view(), name='add_book'),
    path('book/<int:pk>/remove', BookShelfDeleteView.as_view(), name='remove_book'),
]

source/webapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Author(models.Model):
    name = models.CharField(max_length=90, verbose_name="ФИО")
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    date_of_death = models.DateField(blank=True, null=True, verbose_name='Дата смерти')
    biography = models.TextField(max_length=5000, null=True, blank=True, verbose_name='Биография')
    image = models.ImageField(upload_to='author_images', blank=True, null=True, verbose_name="Фотография")
    is_deleted = models.BooleanField(default=False)

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('webapp:author_details', kwargs={'pk': self.pk})


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название")
    author = models.ForeignKey(Author, related_name="books", verbose_name="Автор", on_delete=models.CASCADE)
    year = models.CharField(max_length=10, verbose_name="Год издания")
    file = models.FileField(upload_to='book_files', blank=True, null=True, verbose_name="Файл")
    image = models.ImageField(upload_to='book_images', blank=True, null=True, verbose_name="Фотография")
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('webapp:book_details', kwargs={'pk': self.pk})


class Review(models.Model):
    text = models.TextField(max_length=1000, null=True, blank=True, verbose_name="Текст отзыва")
    author = models.ForeignKey(User, verbose_name="Автор", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, verbose_name="Дата и время создания")
    book = models.ForeignKey(Book, related_name="reviews", blank=True, verbose_name="Книга", on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('webapp:book_details', kwargs={'pk': self.book.id})

    def __str__(self):
        return f"{self.pk}. {self.text} | {self.author.username}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class BookShelf(models.Model):
    user = models.ForeignKey(User, related_name="shelf", verbose_name="Пользователь", on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name="shelf", blank=True, verbose_name="Книга", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Книги на полке"
        verbose_name_plural = "Книги на полке"
        unique_together = ('user', 'book')

    def __str__(self):
        return self.book.title

source/webapp/forms.py
from django import forms
from django.contrib.auth.models import User
from webapp.models import Author, Book, Review


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        date_of_birth = forms.DateField(widget=forms.SelectDateWidget())
        date_of_death = forms.DateField(widget=forms.SelectDateWidget())
        fields = ['name', 'date_of_birth', 'date_of_death', 'image', 'biography']


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'year', 'image', 'file', 'description']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']

source/webapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import UserForm, AuthorForm, BookForm, ReviewForm
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from webapp.models import Author, Book, Review, BookShelf
from django.http import HttpResponse

class UserDetailView(DetailView):
    template_name = 'user_details.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['books'] = self.object.shelf.all()
        return context


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    form_class = UserForm

    def get_success_url(self):
        return reverse('webapp:user_details', kwargs={'pk': self.object.pk})

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        if user != self.request.user:
            return HttpResponseRedirect(reverse('webapp:user_details', kwargs={'pk': pk}))
        return super().get(request, pk=pk)

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().author


class AuthorListView(ListView):
    template_name = 'author_list.html'
    model = Author
    queryset = Author.objects.filter(is_deleted=False)


class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'author_create.html'
    form_class = AuthorForm
    model = Author

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorDetailView(DetailView):
    template_name = 'author_details.html'
    model = Author

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context['books'] = self.object.books.all()
        return context


class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'author_update.html'
    form_class = AuthorForm
    model = Author

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorDeleteView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'author_delete.html'
    model = Author
    success_url = reverse_lazy('webapp:author_list')

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        return HttpResponseRedirect(self.get_success_url())


class BookListView(ListView):
    template_name = 'book_list.html'
    model = Book


class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'book_create.html'
    form_class = BookForm
    model = Book

    def form_valid(self, form):
        return super().form_valid(form)

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class BookDetailView(DetailView):
    template_name = 'book_details.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['reviews'] = self.object.reviews.all().order_by('-created_at')
        return context


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'book_update.html'
    form_class = BookForm
    model = Book

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class BookDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'book_delete.html'
    model = Book
    success_url = reverse_lazy('webapp:book_list')

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class ReviewListView(ListView):
    template_name = 'review_list.html'
    model = Review


class ReviewCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'partial/review_form.html'
    form_class = ReviewForm
    model = Review

    def form_valid(self, form):
        book = get_object_or_404(Book, pk=self.kwargs['pk'])
        form.instance.book = book
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user


class ReviewDetailView(DetailView):
    template_name = 'review_detail.html'
    model = Review


class ReviewUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'review_update.html'
    form_class = ReviewForm
    model = Review

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().author


class ReviewDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'review_delete.html'
    model = Review
    success_url = reverse_lazy('webapp:book_list')

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().author


class BookShelfView(CreateView):

    def get(self, request, pk):
        return HttpResponseRedirect(reverse('webapp:book_detail', kwargs={'pk': pk}))

    def post(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        BookShelf.objects.create(book=book, user=self.request.user)

        return HttpResponse(status=201)


class BookShelfDeleteView(DeleteView, LoginRequiredMixin, PermissionRequiredMixin):

    def get(self, request, pk):
        return HttpResponseRedirect(reverse('webapp:book_detail', kwargs={'pk': pk}))

    def post(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        book_on_shelf = BookShelf.objects.get(book=book, user=self.request.user)
        book_on_shelf.delete()

        return HttpResponse(status=201)

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().user

source/webapp/templates/author_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Новый автор{% endblock %}

{% block content %}
    <h1 class="mt-3">Добавить автора</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:author_create' %}">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-primary mr-1">Отправить</button>
    </form>
{% endblock %}

source/webapp/templates/author_delete.html
{% extends 'base.html' %}

{% block title %}Удалить автора{% endblock %}

{% block content %}
    <h1 class="mt-3">Удаление автора</h1>
    <h5 class="mt-4">Вы уверены, что хотите удалить автора "{{ author.name }}"?</h5>
    <form action="{% url 'webapp:author_delete' author.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mt-2 mr-1">Удалить</button>
        <a class="btn btn-primary mt-2" href="{% url 'webapp:author_list' %}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/author_details.html
{% extends 'base.html' %}

{% block title %}Автор{% endblock %}

{% block content %}
    <div class="container">
        <div class="card mt-4" style="width: 50rem;">
            <div class="card-body">
                {% if author.image %}
                    <img class="card-img-top" src="{{ author.image.url }}" alt="{{ author.image.name }}">
                {% endif %}
                <h4 class="card-title mt-4 mb-4">{{ author.name }}</h4>
                <h6 class="card-subtitle mb-2 text-muted">{{ author.date_of_birth }} - {{ author.date_of_death }}</h6>
                <p class="card-text">{{ author.biography }}</p>
                {% if user.is_staff %}
                    <a class="card-link" href="{% url 'webapp:author_update' author.pk %}">Редактировать</a>
                    <a class="card-link" href="{% url 'webapp:author_delete' author.pk %}">Удалить</a>
                {% endif %}
                <hr/>
                <h5 class="card-title mt-4">Книги:</h5>
                {% include 'partial/book_list.html' with book_list=books %}
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/author_list.html
{% extends 'base.html' %}

{% block title %}Авторы{% endblock %}

{% block content %}
    <div class="container">
        {% for author in author_list %}
            <div class="card mt-4">
                <div class="card-body">
                    {% if author.image %}
                        <a href="{% url 'webapp:author_details' author.pk %}">
                        <img class="card-img-top" src="{{ author.image.url }}" alt="{{ author.image.name }}">
                        </a>
                    {% endif %}
                    <h4 class="card-title mt-4 mb-4">{{ author.name }}</h4>
                    <h6 class="card-subtitle mb-2 text-muted">{{ author.date_of_birth }}
                        - {{ author.date_of_death }}</h6>
                    <p class="card-text">{{ author.biography }}</p>
                    {% if user.is_staff %}
                        <a class="card-link" href="{% url 'webapp:author_update' author.pk %}">Редактировать</a>
                        <a class="card-link" href="{% url 'webapp:author_delete' author.pk %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/author_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменить автора{% endblock %}

{% block content %}
    <h1 class="mt-3">Изменить автора</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:author_update' object.pk %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mr-1">Отправить</button>
    </form>
{% endblock %}

source/webapp/templates/book_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Новая книга{% endblock %}

{% block content %}
    <h1 class="mt-3">Добавить книгу</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:book_create' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mr-1">Отправить</button>
    </form>
{% endblock %}

source/webapp/templates/book_delete.html
{% extends 'base.html' %}

{% block title %}Удалить книгу{% endblock %}

{% block content %}
    <h1 class="mt-3">Удаление книги</h1>
    <h5 class="mt-4">Вы уверены, что хотите удалить книгу "{{ book.title }}"?</h5>
    <form action="{% url 'webapp:book_delete' book.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mt-2 mr-1">Удалить</button>
        <a class="btn btn-primary mt-2" href="{% url 'webapp:book_list' %}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/book_list.html
{% extends 'base.html' %}

{% block title %}Книги{% endblock %}

{% block content %}
    {% for book in book_list %}
        <div class="container">
            <div class="card mt-4" style="width: 50rem;">
                <div class="card-body">
                    {% if book.image %}
                        <a href="{% url "webapp:book_details" book.pk %}">
                            <img class="card-img-top" src="{{ book.image.url }}" alt="{{ book.image.name }}">
                        </a>
                    {% endif %}
                    <h4 class="card-title mt-4 mb-4">{{ book.title }}</h4>
                    {% if user.is_authenticated %}
                        <form method="POST" enctype="multipart/form-data" action="{% url 'webapp:add_book' book.pk %}"
                              id="shelf">
                            {% csrf_token %}
                            <div>
                                <button type="submit" class="btn btn-outline-secondary btn-sm mb-3">Добавить на полку
                            </button>
                            </div>
                        </form>
                    {% endif %}
                    <h6 class="card-subtitle mb-2 text-muted">Год издания: {{ book.year }}</h6>
                    {% if user.is_staff %}
                        <a class="card-link" href="{% url 'webapp:book_update' book.pk %}">Редактировать</a>
                        <a class="card-link" href="{% url 'webapp:book_delete' book.pk %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
     {% endfor %}
        <script language="JavaScript">
        $(document).ready(function () {
            $('#shelf button[type="submit"]').click(function (e) { // catch the form's submit event
                e.preventDefault();
                url = e.target.form.action;
                csrf = $("input[name='csrfmiddlewaretoken']", e.target.form).val();
                div = $("div", e.target.form).get()[0];
                button = $("button", e.target.form).get()[0];
                console.log(div);
                $.ajax({
                    data: {"csrfmiddlewaretoken": csrf},
                    type: e.target.form.method,
                    url: url,
                    success: function (response) { // on success..
                        alert("Вы добавили эту книгу!")
                        div.remove();
                    },
                    error: function (response) {
                        alert("Эта книга уже добавлена!")
                        button.remove();
                    }
                });
                return false;
            });
        })
    </script>
{% endblock %}

source/webapp/templates/review_delete.html
{% extends 'base.html' %}
{% block title %}Удалить отзыв{% endblock %}
{% block content %}
    <h1>Удаление отзыва</h1>
    <h5>Вы уверены, что хотите удалить отзыв?</h5>
    <form action="{% url 'webapp:review_delete' review.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn, btn-primary">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/review_detail.html
{% extends 'base.html' %}

{% block title %}Комментарий{% endblock %}

{% block content %}
    <p>{{ review.author }} | {{ review.created_at }}
        {% if user == review.author %}
            <a class="float-right" href="{% url 'webapp:review_update' article.pk %}">Редактировать</a>
            <a class="float-right" href="{% url 'webapp:review_delete' article.pk %}">Удалить</a>
        {% endif %}
    </p>
    <p class="mt-3 pre-spaces">{{ review.text }}</p>
{% endblock %}

source/webapp/templates/review_list.html
{% block content %}
    {% for review in review_list %}
        <div class="card mt-3 p-1">
            <h5 class="card-title">
                {{ review.text }}
            </h5>
            <p class="card-text">
                <a href="{% url "webapp:user_details" review.author.pk %}">{{ review.author }}</a> | {{ review.created_at }}
            </p>
            <p>
                {% if user == review.author %}
                    <a class="card-link" href="{% url 'webapp:review_update'  review.pk %}">Редактировать</a>
                    <a class="card-link" href="{% url 'webapp:review_delete'  review.pk %}">Удалить</a>
                {% endif %}
            </p>
        </div>
    {% endfor %}
{% endblock %}

source/webapp/templates/review_update.html
{% extends 'base.html' %}
{% block title %}Изменить отзыв{% endblock %}

{% block content %}
    <h1 class="mt-3">Изменить отзыв</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:review_update' object.pk %}">
        {% csrf_token %}
        {% include 'partial/review_form.html' %}
    </form>
{% endblock %}

source/webapp/templates/user_details.html
{% extends 'base.html' %}
{% block title %}Пользователь {% endblock %}
{% block content %}
    <div class="container">
        <div class="card mt-4" style="width: 50rem;">
            <div class="card-body">
                <h4 class="card-title mt-4 mb-4">Пользователь: {{ user }}</h4>
                <p class="card-text">
                <p>Имя: {{ user.first_name }}</p>
                <p>Фамилия: {{ user.last_name }}</p>
                <p>Почта: {{ user.email }}</p>
                </p>
                {% if user == request.user %}
                    <a class="card-link" href="{% url 'webapp:user_update' request.user.pk %}">Редактировать</a>
                {% endif %}
                <hr/>
                <h5 class="card-title mt-4">Книги:</h5>
                {% for book in books %}
                    {% if user.is_authenticated %}
                        <form method="POST" enctype="multipart/form-data"
                              action="{% url 'webapp:remove_book' book.book.pk %}"
                              id="shelf">
                            {% csrf_token %}
                            <div>
                                <a href="{% url 'webapp:book_details' book.book.pk %}"
                                   class="card-link">{{ book.book.title }}</a> {{ book.book.author.name }}
                                    {% if user == request.user %}
                                    <button class="btn btn-outline-secondary btn-sm mb-3" type="submit">Удалить</button>
                                    {% endif %}
                            </div>
                        </form>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <script language="JavaScript">
        $(document).ready(function () {
            $('#shelf button[type="submit"]').click(function (e) { // catch the form's submit event
                e.preventDefault();
                url = e.target.form.action;
                csrf = $("input[name='csrfmiddlewaretoken']", e.target.form).val();
                div = $("div", e.target.form).get()[0];
                console.log(div);
                console.log(e.target.form);
                $.ajax({
                    data: {"csrfmiddlewaretoken": csrf},
                    type: e.target.form.method,
                    url: url,
                    success: function (response) { // on success..
                        alert("success!")
                        div.remove();
                    },
                    error: function (response) {
                        alert("error!")
                    }
                });
                return false;
            });
        })
    </script>
{% endblock %}

source/webapp/templates/user_update.html
{% extends 'base.html' %}

{% block title %}Изменить пользователя{% endblock %}

{% block content %}
    <h1>Изменить пользователя</h1>
    <form action="{% url 'webapp:user_update' form.instance.pk %}" method="post" class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col">
              <input type="text" class="form-control" placeholder="First name" name="first_name" value="{{ user.first_name }}">
            </div>
            <div class="col">
              <input type="text" class="form-control" placeholder="Last name" name="last_name" value="{{ user.last_name }}">
            </div>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email" value={{ user.email }}>
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}